# Generated by Django 2.0.7 on 2020-05-16 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0002_auto_20180727_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='mcqquestion',
            name='question_ptr',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='MCQQuestion',
        ),
    ]
