# Generated by Django 2.0.7 on 2019-02-28 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import quiz.models
import quiz.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0004_csvupload_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('file', models.FileField(upload_to=quiz.models.upload_csv_file, validators=[quiz.validators.question_file_validator])),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
