# Generated by Django 2.0.7 on 2020-05-18 05:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0004_enrollmentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('annual_income', models.IntegerField()),
                ('profession', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
