# Generated by Django 2.0.7 on 2020-05-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_claimmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollmentmodel',
            name='sex',
        ),
        migrations.AddField(
            model_name='enrollmentmodel',
            name='address',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentmodel',
            name='date_of_birth',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentmodel',
            name='dependent_details',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentmodel',
            name='employer_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentmodel',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='enrollmentmodel',
            name='group_plan_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentmodel',
            name='ssn',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentmodel',
            name='work_status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentmodel',
            name='annual_income',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentmodel',
            name='profession',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
