# Generated by Django 2.0.7 on 2019-03-12 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_questionupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='Enter the Chapter text that you want displayed', max_length=1000, verbose_name='Chapter')),
            ],
            options={
                'verbose_name': 'Chapter',
                'ordering': ['content'],
                'verbose_name_plural': 'Chapters',
            },
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='Enter the Standard text that you want displayed', max_length=1000, verbose_name='Class')),
            ],
            options={
                'verbose_name': 'Standard',
                'ordering': ['content'],
                'verbose_name_plural': 'Standard',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='Enter the Subject text that you want displayed', max_length=1000, verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Subject',
                'ordering': ['content'],
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='Enter the Topic text that you want displayed', max_length=1000, verbose_name='Topic')),
                ('chapter_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Chapter')),
                ('standard_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Standard')),
                ('subject_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Subject')),
            ],
            options={
                'verbose_name': 'Topic',
                'ordering': ['content'],
                'verbose_name_plural': 'Topics',
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='standard_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Standard'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Subject'),
        ),
    ]
