# Generated by Django 2.0.7 on 2019-03-13 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20190312_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topic_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Topic'),
        ),
    ]
