# Generated by Django 2.0.7 on 2020-05-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20200518_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimmodel',
            name='age',
        ),
        migrations.RemoveField(
            model_name='claimmodel',
            name='annual_income',
        ),
        migrations.RemoveField(
            model_name='claimmodel',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='claimmodel',
            name='sex',
        ),
        migrations.AddField(
            model_name='claimmodel',
            name='claim_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='claimmodel',
            name='group_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='claimmodel',
            name='ssn',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
