# Generated by Django 2.0.7 on 2019-03-14 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_question_topic_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloomsTaxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='Enter the Blooms Taxonomy you want to display', max_length=1000, verbose_name='Blooms Taxonomy')),
            ],
            options={
                'ordering': ['content'],
                'verbose_name_plural': 'Blooms',
                'verbose_name': 'Blooms',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty_level',
            field=models.CharField(choices=[('Easy', 'easy'), ('Normal', 'normal'), ('Hard', 'hard')], default='Easy', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='blooms_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.BloomsTaxonomy'),
        ),
    ]
